apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: microservices-eCommerce
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:latest
        args: ["start"]
        env:
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-host
        - name: KC_DB_URL_PORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-port
        - name: KC_DB_URL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-name
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: user
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: pass
        - name: KC_PROXY_HEADERS
          value: xforwarded
        - name: KC_HOSTNAME_STRICT
          value: "false" # Cambiar a true cuando se tenga un dominio configurado
        - name: KC_HTTP_RELATIVE_PATH
          value: "/auth"
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        ports:
        - name: http
          containerPort: 8080
