apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: microservices-eCommerce
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: contenedoresjg12345.azurecr.io/api-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
          value: "http://keycloak:8080/auth/realms/microservice-realm"
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          value: "http://zipkin:9411/api/v2/spans"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
