apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: microservices-eCommerce
type: Opaque
stringData:
  user: adminaz
  pass: Rafael27
  db-host: "postgres-testjg.postgres.database.azure.com"
  db-port: "5432"
  db-name: "ms_keycloak"