spring:
  application:
    name: products-service

  datasource:
    url: jdbc:postgresql://postgres-testjg.postgres.database.azure.com:5432/ms_products?sslmode=require
    username: adminaz
    password: Rafael27
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8181/realms/microservice-realm

server:
  port: 8083

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    prometheus:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}  
logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}] - %m%n"
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.sukera: DEBUG 
