spring:
  application:
    name: notification-server


kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: notification-server
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
server:
  port: 0

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    prometheus:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}  
logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}] - %m%n"
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.sukera: DEBUG 